xtalk/login/urls.py
from django.urls import path

from . import views

app_name = "login"

urlpatterns = [
    path("", views.login_form, name="form"),
    path("token/<str:token>/", views.check_token, name="check"),
    path("logout/", views.logout_user, name="logout"),
]

xtalk/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name="home"),
]

if settings.BROWSER_RELOAD:
    urlpatterns += [
        path("__reload__/", include("django_browser_reload.urls")),
    ]

xtalk/login/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser


class UserManager(BaseUserManager):
    def create_user(self, email, password=None):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError("Users must have an email address")

        user = self.model(email=self.normalize_email(email))
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None):
        """
        Creates and saves a superuser with the given email and password.
        """
        user = self.create_user(email, password=password)
        user.is_admin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    email = models.EmailField(verbose_name="email address", max_length=255, unique=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects: UserManager = UserManager()  # type: ignore

    USERNAME_FIELD = "email"

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return self.is_admin

    @property
    def is_staff(self):
        return self.is_admin

xtalk/login/forms.py
from django import forms


class LoginForm(forms.Form):
    email = forms.EmailField()

xtalk/login/views.py
from django.conf import settings
from django.contrib.auth import login, logout
from django.http import HttpResponseNotFound
from django.shortcuts import redirect, render

from xtalk.login import tokens

from .forms import LoginForm


def login_form(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data["email"]
            tokens.send(request, email)
            return render(request, "login/email_sent.html", {"email": email})

    else:
        form = LoginForm()

    return render(request, "login/form.html", {"form": form})


def check_token(request, token):
    user = tokens.check(token)
    if user is None:
        return HttpResponseNotFound()

    login(request, user)
    return redirect(settings.LOGIN_REDIRECT_URL)


def logout_user(request):
    logout(request)
    return redirect(settings.LOGOUT_REDIRECT_URL)

xtalk/views.py
from django.shortcuts import render


def home(request):
    return render(request, "home.html")

xtalk/templates/base.html
{% load static django_htmx %}

<!doctype html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="{% static "tailwind.js" %}"></script>
        <script src="{% static "htmx.js" %}" defer></script>
        {% django_htmx_script %}
    </head>
    <body
        class="dark:bg-slate-800"
        hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
    >
        {% block content %}
        {% endblock %}
    </body>
</html>

xtalk/templates/home.html
{% extends "base.html" %}

{% block content %}
    <div class="prose dark:prose-invert">
        Hello xtalk!
    </div>
{% endblock %}

xtalk/templates/login/email_sent.html
{% extends "base.html" %}

{% block content %}
    <div class="prose dark:prose-invert">
        <p>
            We have sent you an email with a login link.
        </p>
    </div>
{% endblock %}

xtalk/templates/login/form.html
{% extends "base.html" %}

{% block content %}
    <form method="POST" class="prose dark:prose-invert">
        {% csrf_token %}
        <label>
            Email:
            {{ form.email }}
        </label>

        <button type="submit">Send login code</button>
        <input type="hidden" name="next" value="{{ next }}">
    </form>
{% endblock %}

xtalk/templates/nav.html
<nav class="text-right dark:text-slate-400">
    {% if request.user.is_authenticated %}
        {{ request.user.email }}
        <form method="post" action="{% url "login:logout" %}" class="inline-block">
            {% csrf_token %}
            <button type="submit">logout</button>
        </form>
    {% else %}
        <a href="{% url "login:form" %}">login</a>
    {% endif %}
</nav>

xtalk/templates/room.html
{% extends "base.html" %}

{% block content %}
    <div class="prose dark:prose-invert">
        <h1>Chat room {{ room }}</h1>
    </div>
{% endblock %}